SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE `trade_input`  (
  `TRADE_INPUT_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `TRANSCATION_ID` int(11) NULL DEFAULT NULL COMMENT '交易主键',
  `TRADE_ID` int(11) NULL DEFAULT NULL COMMENT '交易员ID',
  `VERSION` int(11) NULL DEFAULT NULL COMMENT '版本号',
  `SECURITY_CODE` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '证券代码',
  `QUANTITY` int(11) NULL DEFAULT NULL COMMENT '数量',
  `OPERATION_TYPE` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '操作类型',
  `SELL_TYPE` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '买卖类型',
  `OPERATION_DATE` datetime(0) NULL DEFAULT NULL COMMENT '操作时间',
  `IS_VALID` char(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '是否有效',
  `REAL_QUANTITY` int(11) NULL DEFAULT NULL COMMENT '实际数量',
  PRIMARY KEY (`TRADE_INPUT_ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 200 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

CREATE TABLE `trade_output`  (
  `TRANSACTION_OUTPUT_ID` int(11) NOT NULL COMMENT '主键',
  `SECURITY_CODE` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '证券代码',
  `QUANTITY` int(11) NULL DEFAULT NULL COMMENT '股票头寸数量',
  PRIMARY KEY (`TRANSACTION_OUTPUT_ID`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

SET FOREIGN_KEY_CHECKS=1;