SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE `trade_input`  (
  `TRANSCATION_ID` int(11) NOT NULL COMMENT '主键',
  `TRADE_ID` int(11) NULL DEFAULT NULL COMMENT '交易员ID',
  `VERSION` int(11) NULL DEFAULT NULL COMMENT '版本号',
  `SECURITY_CODE` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '证券代码',
  `QUANTITY` int(11) NULL DEFAULT NULL COMMENT '数量',
  `OPERATION_TYPE` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '操作类型',
  `SELL_TYPE` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '买卖类型',
  PRIMARY KEY (`TRANSCATION_ID`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

CREATE TABLE `trade_output`  (
  `TRANSACTION_OUTPUT_ID` int(11) NOT NULL COMMENT '主键',
  `SECURITY_CODE` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '证券代码',
  `QUANTITY` int(11) NULL DEFAULT NULL COMMENT '股票头寸数量',
  PRIMARY KEY (`TRANSACTION_OUTPUT_ID`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

SET FOREIGN_KEY_CHECKS=1;