package com.rongwei.pims.job.domain;

import java.io.Serializable;
import java.util.Date;

public class AcOperator implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_OPERATOR.OPERATORID
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private Long operatorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_OPERATOR.USERID
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_OPERATOR.PASSWORD
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_OPERATOR.INVALDATE
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private Date invaldate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_OPERATOR.OPERATORNAME
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private String operatorname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_OPERATOR.AUTHMODE
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private String authmode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_OPERATOR.STATUS
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_OPERATOR.UNLOCKTIME
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private Date unlocktime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_OPERATOR.MENUTYPE
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private String menutype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_OPERATOR.LASTLOGIN
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private Date lastlogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_OPERATOR.ERRCOUNT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private Long errcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_OPERATOR.STARTDATE
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private Date startdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_OPERATOR.ENDDATE
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private Date enddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_OPERATOR.VALIDTIME
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private String validtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_OPERATOR.MACCODE
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private String maccode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_OPERATOR.IPADDRESS
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private String ipaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_OPERATOR.EMAIL
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_OPERATOR.PAGESTYLE
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private String pagestyle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_OPERATOR.CAID
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private String caid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_OPERATOR.CAUSDERID
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private String causderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_OPERATOR.CAEMAIL
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private String caemail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AC_OPERATOR.EMPID
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private String empid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AC_OPERATOR
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_OPERATOR.OPERATORID
     *
     * @return the value of AC_OPERATOR.OPERATORID
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public Long getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_OPERATOR.OPERATORID
     *
     * @param operatorid the value for AC_OPERATOR.OPERATORID
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setOperatorid(Long operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_OPERATOR.USERID
     *
     * @return the value of AC_OPERATOR.USERID
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_OPERATOR.USERID
     *
     * @param userid the value for AC_OPERATOR.USERID
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_OPERATOR.PASSWORD
     *
     * @return the value of AC_OPERATOR.PASSWORD
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_OPERATOR.PASSWORD
     *
     * @param password the value for AC_OPERATOR.PASSWORD
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_OPERATOR.INVALDATE
     *
     * @return the value of AC_OPERATOR.INVALDATE
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public Date getInvaldate() {
        return invaldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_OPERATOR.INVALDATE
     *
     * @param invaldate the value for AC_OPERATOR.INVALDATE
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setInvaldate(Date invaldate) {
        this.invaldate = invaldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_OPERATOR.OPERATORNAME
     *
     * @return the value of AC_OPERATOR.OPERATORNAME
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public String getOperatorname() {
        return operatorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_OPERATOR.OPERATORNAME
     *
     * @param operatorname the value for AC_OPERATOR.OPERATORNAME
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setOperatorname(String operatorname) {
        this.operatorname = operatorname == null ? null : operatorname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_OPERATOR.AUTHMODE
     *
     * @return the value of AC_OPERATOR.AUTHMODE
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public String getAuthmode() {
        return authmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_OPERATOR.AUTHMODE
     *
     * @param authmode the value for AC_OPERATOR.AUTHMODE
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setAuthmode(String authmode) {
        this.authmode = authmode == null ? null : authmode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_OPERATOR.STATUS
     *
     * @return the value of AC_OPERATOR.STATUS
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_OPERATOR.STATUS
     *
     * @param status the value for AC_OPERATOR.STATUS
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_OPERATOR.UNLOCKTIME
     *
     * @return the value of AC_OPERATOR.UNLOCKTIME
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public Date getUnlocktime() {
        return unlocktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_OPERATOR.UNLOCKTIME
     *
     * @param unlocktime the value for AC_OPERATOR.UNLOCKTIME
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setUnlocktime(Date unlocktime) {
        this.unlocktime = unlocktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_OPERATOR.MENUTYPE
     *
     * @return the value of AC_OPERATOR.MENUTYPE
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public String getMenutype() {
        return menutype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_OPERATOR.MENUTYPE
     *
     * @param menutype the value for AC_OPERATOR.MENUTYPE
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setMenutype(String menutype) {
        this.menutype = menutype == null ? null : menutype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_OPERATOR.LASTLOGIN
     *
     * @return the value of AC_OPERATOR.LASTLOGIN
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public Date getLastlogin() {
        return lastlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_OPERATOR.LASTLOGIN
     *
     * @param lastlogin the value for AC_OPERATOR.LASTLOGIN
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setLastlogin(Date lastlogin) {
        this.lastlogin = lastlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_OPERATOR.ERRCOUNT
     *
     * @return the value of AC_OPERATOR.ERRCOUNT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public Long getErrcount() {
        return errcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_OPERATOR.ERRCOUNT
     *
     * @param errcount the value for AC_OPERATOR.ERRCOUNT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setErrcount(Long errcount) {
        this.errcount = errcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_OPERATOR.STARTDATE
     *
     * @return the value of AC_OPERATOR.STARTDATE
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_OPERATOR.STARTDATE
     *
     * @param startdate the value for AC_OPERATOR.STARTDATE
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_OPERATOR.ENDDATE
     *
     * @return the value of AC_OPERATOR.ENDDATE
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_OPERATOR.ENDDATE
     *
     * @param enddate the value for AC_OPERATOR.ENDDATE
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_OPERATOR.VALIDTIME
     *
     * @return the value of AC_OPERATOR.VALIDTIME
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public String getValidtime() {
        return validtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_OPERATOR.VALIDTIME
     *
     * @param validtime the value for AC_OPERATOR.VALIDTIME
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setValidtime(String validtime) {
        this.validtime = validtime == null ? null : validtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_OPERATOR.MACCODE
     *
     * @return the value of AC_OPERATOR.MACCODE
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public String getMaccode() {
        return maccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_OPERATOR.MACCODE
     *
     * @param maccode the value for AC_OPERATOR.MACCODE
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setMaccode(String maccode) {
        this.maccode = maccode == null ? null : maccode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_OPERATOR.IPADDRESS
     *
     * @return the value of AC_OPERATOR.IPADDRESS
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public String getIpaddress() {
        return ipaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_OPERATOR.IPADDRESS
     *
     * @param ipaddress the value for AC_OPERATOR.IPADDRESS
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setIpaddress(String ipaddress) {
        this.ipaddress = ipaddress == null ? null : ipaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_OPERATOR.EMAIL
     *
     * @return the value of AC_OPERATOR.EMAIL
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_OPERATOR.EMAIL
     *
     * @param email the value for AC_OPERATOR.EMAIL
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_OPERATOR.PAGESTYLE
     *
     * @return the value of AC_OPERATOR.PAGESTYLE
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public String getPagestyle() {
        return pagestyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_OPERATOR.PAGESTYLE
     *
     * @param pagestyle the value for AC_OPERATOR.PAGESTYLE
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setPagestyle(String pagestyle) {
        this.pagestyle = pagestyle == null ? null : pagestyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_OPERATOR.CAID
     *
     * @return the value of AC_OPERATOR.CAID
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public String getCaid() {
        return caid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_OPERATOR.CAID
     *
     * @param caid the value for AC_OPERATOR.CAID
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setCaid(String caid) {
        this.caid = caid == null ? null : caid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_OPERATOR.CAUSDERID
     *
     * @return the value of AC_OPERATOR.CAUSDERID
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public String getCausderid() {
        return causderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_OPERATOR.CAUSDERID
     *
     * @param causderid the value for AC_OPERATOR.CAUSDERID
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setCausderid(String causderid) {
        this.causderid = causderid == null ? null : causderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_OPERATOR.CAEMAIL
     *
     * @return the value of AC_OPERATOR.CAEMAIL
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public String getCaemail() {
        return caemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_OPERATOR.CAEMAIL
     *
     * @param caemail the value for AC_OPERATOR.CAEMAIL
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setCaemail(String caemail) {
        this.caemail = caemail == null ? null : caemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AC_OPERATOR.EMPID
     *
     * @return the value of AC_OPERATOR.EMPID
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public String getEmpid() {
        return empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AC_OPERATOR.EMPID
     *
     * @param empid the value for AC_OPERATOR.EMPID
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setEmpid(String empid) {
        this.empid = empid == null ? null : empid.trim();
    }
}