package com.rongwei.pims.job.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class MmContractProject implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_ContractProjectSplit.ContractProjectSplitId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private Integer contractprojectsplitid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_ContractProjectSplit.ContractId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private Integer contractid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_ContractProjectSplit.BidInformId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private Integer bidinformid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_ContractProjectSplit.MMProjectId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private Integer mmprojectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_ContractProjectSplit.PMProjectId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private Integer pmprojectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_ContractProjectSplit.ProjectPhase
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private String projectphase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_ContractProjectSplit.RecordPhase
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private Byte recordphase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_ContractProjectSplit.ForecastPurchaseContract
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private BigDecimal forecastpurchasecontract;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_ContractProjectSplit.ContractMoney
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private BigDecimal contractmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_ContractProjectSplit.SplitPercentage
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private BigDecimal splitpercentage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_ContractProjectSplit.Remark
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_ContractProjectSplit.PreviousVersion
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private String previousversion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_ContractProjectSplit.Version
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_ContractProjectSplit.IsLatestVersion
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private String islatestversion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_ContractProjectSplit.IsDeptSplit
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private String isdeptsplit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_ContractProjectSplit.InvoicedAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private BigDecimal invoicedamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_ContractProjectSplit.CollectedAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private BigDecimal collectedamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_ContractProjectSplit.InsertId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private String insertid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_ContractProjectSplit.InsertTime
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private Date inserttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_ContractProjectSplit.LastUpdateId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private String lastupdateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_ContractProjectSplit.LastUpdateTime
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private Date lastupdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_ContractProjectSplit.ProcessControlType
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private Byte processcontroltype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_ContractProjectSplit.SplitPersonId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private String splitpersonid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_ContractProjectSplit.SplitPerson
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private String splitperson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_ContractProjectSplit.SplitDate
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private Date splitdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_ContractProjectSplit.AdjustedContractMoney
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private BigDecimal adjustedcontractmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_ContractProjectSplit.MainContractMoney
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private BigDecimal maincontractmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_ContractProjectSplit.AdjustedmainContractMoney
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private BigDecimal adjustedmaincontractmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_ContractProjectSplit.PurchaseContractAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private BigDecimal purchasecontractamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MM_ContractProjectSplit
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_ContractProjectSplit.ContractProjectSplitId
     *
     * @return the value of MM_ContractProjectSplit.ContractProjectSplitId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public Integer getContractprojectsplitid() {
        return contractprojectsplitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_ContractProjectSplit.ContractProjectSplitId
     *
     * @param contractprojectsplitid the value for MM_ContractProjectSplit.ContractProjectSplitId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setContractprojectsplitid(Integer contractprojectsplitid) {
        this.contractprojectsplitid = contractprojectsplitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_ContractProjectSplit.ContractId
     *
     * @return the value of MM_ContractProjectSplit.ContractId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public Integer getContractid() {
        return contractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_ContractProjectSplit.ContractId
     *
     * @param contractid the value for MM_ContractProjectSplit.ContractId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setContractid(Integer contractid) {
        this.contractid = contractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_ContractProjectSplit.BidInformId
     *
     * @return the value of MM_ContractProjectSplit.BidInformId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public Integer getBidinformid() {
        return bidinformid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_ContractProjectSplit.BidInformId
     *
     * @param bidinformid the value for MM_ContractProjectSplit.BidInformId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setBidinformid(Integer bidinformid) {
        this.bidinformid = bidinformid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_ContractProjectSplit.MMProjectId
     *
     * @return the value of MM_ContractProjectSplit.MMProjectId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public Integer getMmprojectid() {
        return mmprojectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_ContractProjectSplit.MMProjectId
     *
     * @param mmprojectid the value for MM_ContractProjectSplit.MMProjectId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setMmprojectid(Integer mmprojectid) {
        this.mmprojectid = mmprojectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_ContractProjectSplit.PMProjectId
     *
     * @return the value of MM_ContractProjectSplit.PMProjectId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public Integer getPmprojectid() {
        return pmprojectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_ContractProjectSplit.PMProjectId
     *
     * @param pmprojectid the value for MM_ContractProjectSplit.PMProjectId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setPmprojectid(Integer pmprojectid) {
        this.pmprojectid = pmprojectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_ContractProjectSplit.ProjectPhase
     *
     * @return the value of MM_ContractProjectSplit.ProjectPhase
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public String getProjectphase() {
        return projectphase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_ContractProjectSplit.ProjectPhase
     *
     * @param projectphase the value for MM_ContractProjectSplit.ProjectPhase
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setProjectphase(String projectphase) {
        this.projectphase = projectphase == null ? null : projectphase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_ContractProjectSplit.RecordPhase
     *
     * @return the value of MM_ContractProjectSplit.RecordPhase
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public Byte getRecordphase() {
        return recordphase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_ContractProjectSplit.RecordPhase
     *
     * @param recordphase the value for MM_ContractProjectSplit.RecordPhase
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setRecordphase(Byte recordphase) {
        this.recordphase = recordphase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_ContractProjectSplit.ForecastPurchaseContract
     *
     * @return the value of MM_ContractProjectSplit.ForecastPurchaseContract
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public BigDecimal getForecastpurchasecontract() {
        return forecastpurchasecontract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_ContractProjectSplit.ForecastPurchaseContract
     *
     * @param forecastpurchasecontract the value for MM_ContractProjectSplit.ForecastPurchaseContract
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setForecastpurchasecontract(BigDecimal forecastpurchasecontract) {
        this.forecastpurchasecontract = forecastpurchasecontract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_ContractProjectSplit.ContractMoney
     *
     * @return the value of MM_ContractProjectSplit.ContractMoney
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public BigDecimal getContractmoney() {
        return contractmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_ContractProjectSplit.ContractMoney
     *
     * @param contractmoney the value for MM_ContractProjectSplit.ContractMoney
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setContractmoney(BigDecimal contractmoney) {
        this.contractmoney = contractmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_ContractProjectSplit.SplitPercentage
     *
     * @return the value of MM_ContractProjectSplit.SplitPercentage
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public BigDecimal getSplitpercentage() {
        return splitpercentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_ContractProjectSplit.SplitPercentage
     *
     * @param splitpercentage the value for MM_ContractProjectSplit.SplitPercentage
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setSplitpercentage(BigDecimal splitpercentage) {
        this.splitpercentage = splitpercentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_ContractProjectSplit.Remark
     *
     * @return the value of MM_ContractProjectSplit.Remark
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_ContractProjectSplit.Remark
     *
     * @param remark the value for MM_ContractProjectSplit.Remark
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_ContractProjectSplit.PreviousVersion
     *
     * @return the value of MM_ContractProjectSplit.PreviousVersion
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public String getPreviousversion() {
        return previousversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_ContractProjectSplit.PreviousVersion
     *
     * @param previousversion the value for MM_ContractProjectSplit.PreviousVersion
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setPreviousversion(String previousversion) {
        this.previousversion = previousversion == null ? null : previousversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_ContractProjectSplit.Version
     *
     * @return the value of MM_ContractProjectSplit.Version
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_ContractProjectSplit.Version
     *
     * @param version the value for MM_ContractProjectSplit.Version
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_ContractProjectSplit.IsLatestVersion
     *
     * @return the value of MM_ContractProjectSplit.IsLatestVersion
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public String getIslatestversion() {
        return islatestversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_ContractProjectSplit.IsLatestVersion
     *
     * @param islatestversion the value for MM_ContractProjectSplit.IsLatestVersion
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setIslatestversion(String islatestversion) {
        this.islatestversion = islatestversion == null ? null : islatestversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_ContractProjectSplit.IsDeptSplit
     *
     * @return the value of MM_ContractProjectSplit.IsDeptSplit
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public String getIsdeptsplit() {
        return isdeptsplit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_ContractProjectSplit.IsDeptSplit
     *
     * @param isdeptsplit the value for MM_ContractProjectSplit.IsDeptSplit
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setIsdeptsplit(String isdeptsplit) {
        this.isdeptsplit = isdeptsplit == null ? null : isdeptsplit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_ContractProjectSplit.InvoicedAmount
     *
     * @return the value of MM_ContractProjectSplit.InvoicedAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public BigDecimal getInvoicedamount() {
        return invoicedamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_ContractProjectSplit.InvoicedAmount
     *
     * @param invoicedamount the value for MM_ContractProjectSplit.InvoicedAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setInvoicedamount(BigDecimal invoicedamount) {
        this.invoicedamount = invoicedamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_ContractProjectSplit.CollectedAmount
     *
     * @return the value of MM_ContractProjectSplit.CollectedAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public BigDecimal getCollectedamount() {
        return collectedamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_ContractProjectSplit.CollectedAmount
     *
     * @param collectedamount the value for MM_ContractProjectSplit.CollectedAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setCollectedamount(BigDecimal collectedamount) {
        this.collectedamount = collectedamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_ContractProjectSplit.InsertId
     *
     * @return the value of MM_ContractProjectSplit.InsertId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public String getInsertid() {
        return insertid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_ContractProjectSplit.InsertId
     *
     * @param insertid the value for MM_ContractProjectSplit.InsertId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setInsertid(String insertid) {
        this.insertid = insertid == null ? null : insertid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_ContractProjectSplit.InsertTime
     *
     * @return the value of MM_ContractProjectSplit.InsertTime
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public Date getInserttime() {
        return inserttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_ContractProjectSplit.InsertTime
     *
     * @param inserttime the value for MM_ContractProjectSplit.InsertTime
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setInserttime(Date inserttime) {
        this.inserttime = inserttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_ContractProjectSplit.LastUpdateId
     *
     * @return the value of MM_ContractProjectSplit.LastUpdateId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public String getLastupdateid() {
        return lastupdateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_ContractProjectSplit.LastUpdateId
     *
     * @param lastupdateid the value for MM_ContractProjectSplit.LastUpdateId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setLastupdateid(String lastupdateid) {
        this.lastupdateid = lastupdateid == null ? null : lastupdateid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_ContractProjectSplit.LastUpdateTime
     *
     * @return the value of MM_ContractProjectSplit.LastUpdateTime
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public Date getLastupdatetime() {
        return lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_ContractProjectSplit.LastUpdateTime
     *
     * @param lastupdatetime the value for MM_ContractProjectSplit.LastUpdateTime
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setLastupdatetime(Date lastupdatetime) {
        this.lastupdatetime = lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_ContractProjectSplit.ProcessControlType
     *
     * @return the value of MM_ContractProjectSplit.ProcessControlType
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public Byte getProcesscontroltype() {
        return processcontroltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_ContractProjectSplit.ProcessControlType
     *
     * @param processcontroltype the value for MM_ContractProjectSplit.ProcessControlType
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setProcesscontroltype(Byte processcontroltype) {
        this.processcontroltype = processcontroltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_ContractProjectSplit.SplitPersonId
     *
     * @return the value of MM_ContractProjectSplit.SplitPersonId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public String getSplitpersonid() {
        return splitpersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_ContractProjectSplit.SplitPersonId
     *
     * @param splitpersonid the value for MM_ContractProjectSplit.SplitPersonId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setSplitpersonid(String splitpersonid) {
        this.splitpersonid = splitpersonid == null ? null : splitpersonid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_ContractProjectSplit.SplitPerson
     *
     * @return the value of MM_ContractProjectSplit.SplitPerson
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public String getSplitperson() {
        return splitperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_ContractProjectSplit.SplitPerson
     *
     * @param splitperson the value for MM_ContractProjectSplit.SplitPerson
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setSplitperson(String splitperson) {
        this.splitperson = splitperson == null ? null : splitperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_ContractProjectSplit.SplitDate
     *
     * @return the value of MM_ContractProjectSplit.SplitDate
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public Date getSplitdate() {
        return splitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_ContractProjectSplit.SplitDate
     *
     * @param splitdate the value for MM_ContractProjectSplit.SplitDate
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setSplitdate(Date splitdate) {
        this.splitdate = splitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_ContractProjectSplit.AdjustedContractMoney
     *
     * @return the value of MM_ContractProjectSplit.AdjustedContractMoney
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public BigDecimal getAdjustedcontractmoney() {
        return adjustedcontractmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_ContractProjectSplit.AdjustedContractMoney
     *
     * @param adjustedcontractmoney the value for MM_ContractProjectSplit.AdjustedContractMoney
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setAdjustedcontractmoney(BigDecimal adjustedcontractmoney) {
        this.adjustedcontractmoney = adjustedcontractmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_ContractProjectSplit.MainContractMoney
     *
     * @return the value of MM_ContractProjectSplit.MainContractMoney
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public BigDecimal getMaincontractmoney() {
        return maincontractmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_ContractProjectSplit.MainContractMoney
     *
     * @param maincontractmoney the value for MM_ContractProjectSplit.MainContractMoney
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setMaincontractmoney(BigDecimal maincontractmoney) {
        this.maincontractmoney = maincontractmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_ContractProjectSplit.AdjustedmainContractMoney
     *
     * @return the value of MM_ContractProjectSplit.AdjustedmainContractMoney
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public BigDecimal getAdjustedmaincontractmoney() {
        return adjustedmaincontractmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_ContractProjectSplit.AdjustedmainContractMoney
     *
     * @param adjustedmaincontractmoney the value for MM_ContractProjectSplit.AdjustedmainContractMoney
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setAdjustedmaincontractmoney(BigDecimal adjustedmaincontractmoney) {
        this.adjustedmaincontractmoney = adjustedmaincontractmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_ContractProjectSplit.PurchaseContractAmount
     *
     * @return the value of MM_ContractProjectSplit.PurchaseContractAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public BigDecimal getPurchasecontractamount() {
        return purchasecontractamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_ContractProjectSplit.PurchaseContractAmount
     *
     * @param purchasecontractamount the value for MM_ContractProjectSplit.PurchaseContractAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setPurchasecontractamount(BigDecimal purchasecontractamount) {
        this.purchasecontractamount = purchasecontractamount;
    }
}