package com.rongwei.pims.job.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class MmProjectAnnualDailyExpenses implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_Project_Annual_Daily_Expenses.ProjectAnnualDailyExpensesId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private Integer projectannualdailyexpensesid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_Project_Annual_Daily_Expenses.ProjectId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private Integer projectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_Project_Annual_Daily_Expenses.ContractId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private Integer contractid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_Project_Annual_Daily_Expenses.RevenusAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private BigDecimal revenusamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_Project_Annual_Daily_Expenses.TotalRevenusAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private BigDecimal totalrevenusamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_Project_Annual_Daily_Expenses.PurchaseCostAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private BigDecimal purchasecostamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_Project_Annual_Daily_Expenses.TotalPurchaseCostAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private BigDecimal totalpurchasecostamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_Project_Annual_Daily_Expenses.ReceiveMoneyAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private BigDecimal receivemoneyamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_Project_Annual_Daily_Expenses.TotalReceiveMoneyAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private BigDecimal totalreceivemoneyamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_Project_Annual_Daily_Expenses.DailyCostAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private BigDecimal dailycostamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_Project_Annual_Daily_Expenses.TotalDailyCostAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private BigDecimal totaldailycostamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_Project_Annual_Daily_Expenses.insertTime
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private Date inserttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_Project_Annual_Daily_Expenses.Year
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private Integer year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_Project_Annual_Daily_Expenses.paidMoneyAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private BigDecimal paidmoneyamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_Project_Annual_Daily_Expenses.totalpaidMoneyAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private BigDecimal totalpaidmoneyamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_Project_Annual_Daily_Expenses.AnnualPurchaseRemaindAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private BigDecimal annualpurchaseremaindamount;
    private BigDecimal lastannualpurchaseremaindamount;

    private BigDecimal annualaddpurchaseremaindamount;

    //annualaddpurchaseremaindamount

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MM_Project_Annual_Daily_Expenses.MMProjectCode
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private String mmprojectcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MM_Project_Annual_Daily_Expenses
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_Project_Annual_Daily_Expenses.ProjectAnnualDailyExpensesId
     *
     * @return the value of MM_Project_Annual_Daily_Expenses.ProjectAnnualDailyExpensesId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public Integer getProjectannualdailyexpensesid() {
        return projectannualdailyexpensesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_Project_Annual_Daily_Expenses.ProjectAnnualDailyExpensesId
     *
     * @param projectannualdailyexpensesid the value for MM_Project_Annual_Daily_Expenses.ProjectAnnualDailyExpensesId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setProjectannualdailyexpensesid(Integer projectannualdailyexpensesid) {
        this.projectannualdailyexpensesid = projectannualdailyexpensesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_Project_Annual_Daily_Expenses.ProjectId
     *
     * @return the value of MM_Project_Annual_Daily_Expenses.ProjectId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public Integer getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_Project_Annual_Daily_Expenses.ProjectId
     *
     * @param projectid the value for MM_Project_Annual_Daily_Expenses.ProjectId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_Project_Annual_Daily_Expenses.ContractId
     *
     * @return the value of MM_Project_Annual_Daily_Expenses.ContractId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public Integer getContractid() {
        return contractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_Project_Annual_Daily_Expenses.ContractId
     *
     * @param contractid the value for MM_Project_Annual_Daily_Expenses.ContractId
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setContractid(Integer contractid) {
        this.contractid = contractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_Project_Annual_Daily_Expenses.RevenusAmount
     *
     * @return the value of MM_Project_Annual_Daily_Expenses.RevenusAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public BigDecimal getRevenusamount() {
        return revenusamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_Project_Annual_Daily_Expenses.RevenusAmount
     *
     * @param revenusamount the value for MM_Project_Annual_Daily_Expenses.RevenusAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setRevenusamount(BigDecimal revenusamount) {
        this.revenusamount = revenusamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_Project_Annual_Daily_Expenses.TotalRevenusAmount
     *
     * @return the value of MM_Project_Annual_Daily_Expenses.TotalRevenusAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public BigDecimal getTotalrevenusamount() {
        return totalrevenusamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_Project_Annual_Daily_Expenses.TotalRevenusAmount
     *
     * @param totalrevenusamount the value for MM_Project_Annual_Daily_Expenses.TotalRevenusAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setTotalrevenusamount(BigDecimal totalrevenusamount) {
        this.totalrevenusamount = totalrevenusamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_Project_Annual_Daily_Expenses.PurchaseCostAmount
     *
     * @return the value of MM_Project_Annual_Daily_Expenses.PurchaseCostAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public BigDecimal getPurchasecostamount() {
        return purchasecostamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_Project_Annual_Daily_Expenses.PurchaseCostAmount
     *
     * @param purchasecostamount the value for MM_Project_Annual_Daily_Expenses.PurchaseCostAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setPurchasecostamount(BigDecimal purchasecostamount) {
        this.purchasecostamount = purchasecostamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_Project_Annual_Daily_Expenses.TotalPurchaseCostAmount
     *
     * @return the value of MM_Project_Annual_Daily_Expenses.TotalPurchaseCostAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public BigDecimal getTotalpurchasecostamount() {
        return totalpurchasecostamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_Project_Annual_Daily_Expenses.TotalPurchaseCostAmount
     *
     * @param totalpurchasecostamount the value for MM_Project_Annual_Daily_Expenses.TotalPurchaseCostAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setTotalpurchasecostamount(BigDecimal totalpurchasecostamount) {
        this.totalpurchasecostamount = totalpurchasecostamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_Project_Annual_Daily_Expenses.ReceiveMoneyAmount
     *
     * @return the value of MM_Project_Annual_Daily_Expenses.ReceiveMoneyAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public BigDecimal getReceivemoneyamount() {
        return receivemoneyamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_Project_Annual_Daily_Expenses.ReceiveMoneyAmount
     *
     * @param receivemoneyamount the value for MM_Project_Annual_Daily_Expenses.ReceiveMoneyAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setReceivemoneyamount(BigDecimal receivemoneyamount) {
        this.receivemoneyamount = receivemoneyamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_Project_Annual_Daily_Expenses.TotalReceiveMoneyAmount
     *
     * @return the value of MM_Project_Annual_Daily_Expenses.TotalReceiveMoneyAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public BigDecimal getTotalreceivemoneyamount() {
        return totalreceivemoneyamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_Project_Annual_Daily_Expenses.TotalReceiveMoneyAmount
     *
     * @param totalreceivemoneyamount the value for MM_Project_Annual_Daily_Expenses.TotalReceiveMoneyAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setTotalreceivemoneyamount(BigDecimal totalreceivemoneyamount) {
        this.totalreceivemoneyamount = totalreceivemoneyamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_Project_Annual_Daily_Expenses.DailyCostAmount
     *
     * @return the value of MM_Project_Annual_Daily_Expenses.DailyCostAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public BigDecimal getDailycostamount() {
        return dailycostamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_Project_Annual_Daily_Expenses.DailyCostAmount
     *
     * @param dailycostamount the value for MM_Project_Annual_Daily_Expenses.DailyCostAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setDailycostamount(BigDecimal dailycostamount) {
        this.dailycostamount = dailycostamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_Project_Annual_Daily_Expenses.TotalDailyCostAmount
     *
     * @return the value of MM_Project_Annual_Daily_Expenses.TotalDailyCostAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public BigDecimal getTotaldailycostamount() {
        return totaldailycostamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_Project_Annual_Daily_Expenses.TotalDailyCostAmount
     *
     * @param totaldailycostamount the value for MM_Project_Annual_Daily_Expenses.TotalDailyCostAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setTotaldailycostamount(BigDecimal totaldailycostamount) {
        this.totaldailycostamount = totaldailycostamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_Project_Annual_Daily_Expenses.insertTime
     *
     * @return the value of MM_Project_Annual_Daily_Expenses.insertTime
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public Date getInserttime() {
        return inserttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_Project_Annual_Daily_Expenses.insertTime
     *
     * @param inserttime the value for MM_Project_Annual_Daily_Expenses.insertTime
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setInserttime(Date inserttime) {
        this.inserttime = inserttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_Project_Annual_Daily_Expenses.Year
     *
     * @return the value of MM_Project_Annual_Daily_Expenses.Year
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_Project_Annual_Daily_Expenses.Year
     *
     * @param year the value for MM_Project_Annual_Daily_Expenses.Year
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_Project_Annual_Daily_Expenses.paidMoneyAmount
     *
     * @return the value of MM_Project_Annual_Daily_Expenses.paidMoneyAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public BigDecimal getPaidmoneyamount() {
        return paidmoneyamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_Project_Annual_Daily_Expenses.paidMoneyAmount
     *
     * @param paidmoneyamount the value for MM_Project_Annual_Daily_Expenses.paidMoneyAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setPaidmoneyamount(BigDecimal paidmoneyamount) {
        this.paidmoneyamount = paidmoneyamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_Project_Annual_Daily_Expenses.totalpaidMoneyAmount
     *
     * @return the value of MM_Project_Annual_Daily_Expenses.totalpaidMoneyAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public BigDecimal getTotalpaidmoneyamount() {
        return totalpaidmoneyamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_Project_Annual_Daily_Expenses.totalpaidMoneyAmount
     *
     * @param totalpaidmoneyamount the value for MM_Project_Annual_Daily_Expenses.totalpaidMoneyAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setTotalpaidmoneyamount(BigDecimal totalpaidmoneyamount) {
        this.totalpaidmoneyamount = totalpaidmoneyamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_Project_Annual_Daily_Expenses.AnnualPurchaseRemaindAmount
     *
     * @return the value of MM_Project_Annual_Daily_Expenses.AnnualPurchaseRemaindAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public BigDecimal getAnnualpurchaseremaindamount() {
        return annualpurchaseremaindamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_Project_Annual_Daily_Expenses.AnnualPurchaseRemaindAmount
     *
     * @param annualpurchaseremaindamount the value for MM_Project_Annual_Daily_Expenses.AnnualPurchaseRemaindAmount
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setAnnualpurchaseremaindamount(BigDecimal annualpurchaseremaindamount) {
        this.annualpurchaseremaindamount = annualpurchaseremaindamount;
    }

    public BigDecimal getLastannualpurchaseremaindamount() {
        return lastannualpurchaseremaindamount;
    }


    public void setLastannualpurchaseremaindamount(BigDecimal lastannualpurchaseremaindamount) {
        this.lastannualpurchaseremaindamount = lastannualpurchaseremaindamount;
    }

    public BigDecimal getAnnualaddpurchaseremaindamount() {
        return annualaddpurchaseremaindamount;
    }


    public void setAnnualaddpurchaseremaindamount(BigDecimal annualaddpurchaseremaindamount) {
        this.annualaddpurchaseremaindamount = annualaddpurchaseremaindamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MM_Project_Annual_Daily_Expenses.MMProjectCode
     *
     * @return the value of MM_Project_Annual_Daily_Expenses.MMProjectCode
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public String getMmprojectcode() {
        return mmprojectcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MM_Project_Annual_Daily_Expenses.MMProjectCode
     *
     * @param mmprojectcode the value for MM_Project_Annual_Daily_Expenses.MMProjectCode
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    public void setMmprojectcode(String mmprojectcode) {
        this.mmprojectcode = mmprojectcode == null ? null : mmprojectcode.trim();
    }
}