package com.rongwei.pims.job.domain;

import java.io.Serializable;
import java.math.BigDecimal;

public class PrFinanceCapitalAnnualDept implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.FINANCE_CAPITAL_ANNUAL_DEPT_ID
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private Integer financeCapitalAnnualDeptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.YEAR
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private Integer year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.DEPT_ID
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.DEPT_NAME
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.DOMESTIC_COLLECTION_AMOUNT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private BigDecimal domesticCollectionAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.FOREIGN_COLLECTION_AMOUNT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private BigDecimal foreignCollectionAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.TRANSFER_AMOUNT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private BigDecimal transferAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.TOTAL_COLLECTION
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private BigDecimal totalCollection;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.GOGAL
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private BigDecimal gogal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.COLLECTION_RATIO
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private BigDecimal collectionRatio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.LASTYEAR_COLLECTION
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private BigDecimal lastyearCollection;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.YEAR_COLLECTION_RATIO
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private BigDecimal yearCollectionRatio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.DOMESTIC_PAYMENT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private BigDecimal domesticPayment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.FOREIGN_PAYMENT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private BigDecimal foreignPayment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.LASTYEAR_PAYMENT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private BigDecimal lastyearPayment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.YEAR_PAYMENT_RATIO
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private BigDecimal yearPaymentRatio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.CAPITAL_AMOUNT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private BigDecimal capitalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.ORDER_COLUMN
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private BigDecimal orderColumn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.IS_REALTIME
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private String isRealtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.CORPORATION_ID
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private Integer corporationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.CORPORATION_NAME
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private String corporationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.LAST_DOMESTIC_COLLECTION_AMOUNT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private BigDecimal lastDomesticCollectionAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.LAST_FOREIGN_COLLECTION_AMOUNT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private BigDecimal lastForeignCollectionAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.LAST_TRANSFER_AMOUNT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private BigDecimal lastTransferAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.LAST_DOMESTIC_PAYMENT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private BigDecimal lastDomesticPayment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.LAST_FOREIGN_PAYMENT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private BigDecimal lastForeignPayment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.TOTAL_PAYMENT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private BigDecimal totalPayment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.RATIO_TO_ALL
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private BigDecimal ratioToAll;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.SALES_TAX_AMOUNT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private BigDecimal salesTaxAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.CASH_BALANCE
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private BigDecimal cashBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.internal_money
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private BigDecimal internalMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.subcontract_payment
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private BigDecimal subcontractPayment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.includ_self_payment
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private BigDecimal includSelfPayment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.AnnualPurchaseRemaindAmount
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private BigDecimal annualpurchaseremaindamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.DeptDailyRemaindAmount
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private BigDecimal deptdailyremaindamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PR_FINANCE_CAPITAL_ANNUAL_DEPT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.FINANCE_CAPITAL_ANNUAL_DEPT_ID
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.FINANCE_CAPITAL_ANNUAL_DEPT_ID
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public Integer getFinanceCapitalAnnualDeptId() {
        return financeCapitalAnnualDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.FINANCE_CAPITAL_ANNUAL_DEPT_ID
     *
     * @param financeCapitalAnnualDeptId the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.FINANCE_CAPITAL_ANNUAL_DEPT_ID
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setFinanceCapitalAnnualDeptId(Integer financeCapitalAnnualDeptId) {
        this.financeCapitalAnnualDeptId = financeCapitalAnnualDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.YEAR
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.YEAR
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.YEAR
     *
     * @param year the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.YEAR
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.DEPT_ID
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.DEPT_ID
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.DEPT_ID
     *
     * @param deptId the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.DEPT_ID
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.DEPT_NAME
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.DEPT_NAME
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.DEPT_NAME
     *
     * @param deptName the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.DEPT_NAME
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.DOMESTIC_COLLECTION_AMOUNT
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.DOMESTIC_COLLECTION_AMOUNT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public BigDecimal getDomesticCollectionAmount() {
        return domesticCollectionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.DOMESTIC_COLLECTION_AMOUNT
     *
     * @param domesticCollectionAmount the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.DOMESTIC_COLLECTION_AMOUNT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setDomesticCollectionAmount(BigDecimal domesticCollectionAmount) {
        this.domesticCollectionAmount = domesticCollectionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.FOREIGN_COLLECTION_AMOUNT
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.FOREIGN_COLLECTION_AMOUNT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public BigDecimal getForeignCollectionAmount() {
        return foreignCollectionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.FOREIGN_COLLECTION_AMOUNT
     *
     * @param foreignCollectionAmount the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.FOREIGN_COLLECTION_AMOUNT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setForeignCollectionAmount(BigDecimal foreignCollectionAmount) {
        this.foreignCollectionAmount = foreignCollectionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.TRANSFER_AMOUNT
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.TRANSFER_AMOUNT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public BigDecimal getTransferAmount() {
        return transferAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.TRANSFER_AMOUNT
     *
     * @param transferAmount the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.TRANSFER_AMOUNT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setTransferAmount(BigDecimal transferAmount) {
        this.transferAmount = transferAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.TOTAL_COLLECTION
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.TOTAL_COLLECTION
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public BigDecimal getTotalCollection() {
        return totalCollection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.TOTAL_COLLECTION
     *
     * @param totalCollection the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.TOTAL_COLLECTION
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setTotalCollection(BigDecimal totalCollection) {
        this.totalCollection = totalCollection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.GOGAL
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.GOGAL
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public BigDecimal getGogal() {
        return gogal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.GOGAL
     *
     * @param gogal the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.GOGAL
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setGogal(BigDecimal gogal) {
        this.gogal = gogal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.COLLECTION_RATIO
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.COLLECTION_RATIO
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public BigDecimal getCollectionRatio() {
        return collectionRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.COLLECTION_RATIO
     *
     * @param collectionRatio the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.COLLECTION_RATIO
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setCollectionRatio(BigDecimal collectionRatio) {
        this.collectionRatio = collectionRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.LASTYEAR_COLLECTION
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.LASTYEAR_COLLECTION
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public BigDecimal getLastyearCollection() {
        return lastyearCollection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.LASTYEAR_COLLECTION
     *
     * @param lastyearCollection the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.LASTYEAR_COLLECTION
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setLastyearCollection(BigDecimal lastyearCollection) {
        this.lastyearCollection = lastyearCollection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.YEAR_COLLECTION_RATIO
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.YEAR_COLLECTION_RATIO
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public BigDecimal getYearCollectionRatio() {
        return yearCollectionRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.YEAR_COLLECTION_RATIO
     *
     * @param yearCollectionRatio the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.YEAR_COLLECTION_RATIO
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setYearCollectionRatio(BigDecimal yearCollectionRatio) {
        this.yearCollectionRatio = yearCollectionRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.DOMESTIC_PAYMENT
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.DOMESTIC_PAYMENT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public BigDecimal getDomesticPayment() {
        return domesticPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.DOMESTIC_PAYMENT
     *
     * @param domesticPayment the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.DOMESTIC_PAYMENT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setDomesticPayment(BigDecimal domesticPayment) {
        this.domesticPayment = domesticPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.FOREIGN_PAYMENT
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.FOREIGN_PAYMENT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public BigDecimal getForeignPayment() {
        return foreignPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.FOREIGN_PAYMENT
     *
     * @param foreignPayment the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.FOREIGN_PAYMENT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setForeignPayment(BigDecimal foreignPayment) {
        this.foreignPayment = foreignPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.LASTYEAR_PAYMENT
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.LASTYEAR_PAYMENT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public BigDecimal getLastyearPayment() {
        return lastyearPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.LASTYEAR_PAYMENT
     *
     * @param lastyearPayment the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.LASTYEAR_PAYMENT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setLastyearPayment(BigDecimal lastyearPayment) {
        this.lastyearPayment = lastyearPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.YEAR_PAYMENT_RATIO
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.YEAR_PAYMENT_RATIO
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public BigDecimal getYearPaymentRatio() {
        return yearPaymentRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.YEAR_PAYMENT_RATIO
     *
     * @param yearPaymentRatio the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.YEAR_PAYMENT_RATIO
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setYearPaymentRatio(BigDecimal yearPaymentRatio) {
        this.yearPaymentRatio = yearPaymentRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.CAPITAL_AMOUNT
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.CAPITAL_AMOUNT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public BigDecimal getCapitalAmount() {
        return capitalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.CAPITAL_AMOUNT
     *
     * @param capitalAmount the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.CAPITAL_AMOUNT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setCapitalAmount(BigDecimal capitalAmount) {
        this.capitalAmount = capitalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.ORDER_COLUMN
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.ORDER_COLUMN
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public BigDecimal getOrderColumn() {
        return orderColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.ORDER_COLUMN
     *
     * @param orderColumn the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.ORDER_COLUMN
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setOrderColumn(BigDecimal orderColumn) {
        this.orderColumn = orderColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.IS_REALTIME
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.IS_REALTIME
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public String getIsRealtime() {
        return isRealtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.IS_REALTIME
     *
     * @param isRealtime the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.IS_REALTIME
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setIsRealtime(String isRealtime) {
        this.isRealtime = isRealtime == null ? null : isRealtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.CORPORATION_ID
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.CORPORATION_ID
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public Integer getCorporationId() {
        return corporationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.CORPORATION_ID
     *
     * @param corporationId the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.CORPORATION_ID
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setCorporationId(Integer corporationId) {
        this.corporationId = corporationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.CORPORATION_NAME
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.CORPORATION_NAME
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public String getCorporationName() {
        return corporationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.CORPORATION_NAME
     *
     * @param corporationName the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.CORPORATION_NAME
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setCorporationName(String corporationName) {
        this.corporationName = corporationName == null ? null : corporationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.LAST_DOMESTIC_COLLECTION_AMOUNT
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.LAST_DOMESTIC_COLLECTION_AMOUNT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public BigDecimal getLastDomesticCollectionAmount() {
        return lastDomesticCollectionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.LAST_DOMESTIC_COLLECTION_AMOUNT
     *
     * @param lastDomesticCollectionAmount the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.LAST_DOMESTIC_COLLECTION_AMOUNT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setLastDomesticCollectionAmount(BigDecimal lastDomesticCollectionAmount) {
        this.lastDomesticCollectionAmount = lastDomesticCollectionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.LAST_FOREIGN_COLLECTION_AMOUNT
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.LAST_FOREIGN_COLLECTION_AMOUNT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public BigDecimal getLastForeignCollectionAmount() {
        return lastForeignCollectionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.LAST_FOREIGN_COLLECTION_AMOUNT
     *
     * @param lastForeignCollectionAmount the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.LAST_FOREIGN_COLLECTION_AMOUNT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setLastForeignCollectionAmount(BigDecimal lastForeignCollectionAmount) {
        this.lastForeignCollectionAmount = lastForeignCollectionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.LAST_TRANSFER_AMOUNT
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.LAST_TRANSFER_AMOUNT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public BigDecimal getLastTransferAmount() {
        return lastTransferAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.LAST_TRANSFER_AMOUNT
     *
     * @param lastTransferAmount the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.LAST_TRANSFER_AMOUNT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setLastTransferAmount(BigDecimal lastTransferAmount) {
        this.lastTransferAmount = lastTransferAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.LAST_DOMESTIC_PAYMENT
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.LAST_DOMESTIC_PAYMENT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public BigDecimal getLastDomesticPayment() {
        return lastDomesticPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.LAST_DOMESTIC_PAYMENT
     *
     * @param lastDomesticPayment the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.LAST_DOMESTIC_PAYMENT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setLastDomesticPayment(BigDecimal lastDomesticPayment) {
        this.lastDomesticPayment = lastDomesticPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.LAST_FOREIGN_PAYMENT
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.LAST_FOREIGN_PAYMENT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public BigDecimal getLastForeignPayment() {
        return lastForeignPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.LAST_FOREIGN_PAYMENT
     *
     * @param lastForeignPayment the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.LAST_FOREIGN_PAYMENT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setLastForeignPayment(BigDecimal lastForeignPayment) {
        this.lastForeignPayment = lastForeignPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.TOTAL_PAYMENT
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.TOTAL_PAYMENT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public BigDecimal getTotalPayment() {
        return totalPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.TOTAL_PAYMENT
     *
     * @param totalPayment the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.TOTAL_PAYMENT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setTotalPayment(BigDecimal totalPayment) {
        this.totalPayment = totalPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.RATIO_TO_ALL
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.RATIO_TO_ALL
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public BigDecimal getRatioToAll() {
        return ratioToAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.RATIO_TO_ALL
     *
     * @param ratioToAll the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.RATIO_TO_ALL
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setRatioToAll(BigDecimal ratioToAll) {
        this.ratioToAll = ratioToAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.SALES_TAX_AMOUNT
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.SALES_TAX_AMOUNT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public BigDecimal getSalesTaxAmount() {
        return salesTaxAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.SALES_TAX_AMOUNT
     *
     * @param salesTaxAmount the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.SALES_TAX_AMOUNT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setSalesTaxAmount(BigDecimal salesTaxAmount) {
        this.salesTaxAmount = salesTaxAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.CASH_BALANCE
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.CASH_BALANCE
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public BigDecimal getCashBalance() {
        return cashBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.CASH_BALANCE
     *
     * @param cashBalance the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.CASH_BALANCE
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setCashBalance(BigDecimal cashBalance) {
        this.cashBalance = cashBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.internal_money
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.internal_money
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public BigDecimal getInternalMoney() {
        return internalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.internal_money
     *
     * @param internalMoney the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.internal_money
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setInternalMoney(BigDecimal internalMoney) {
        this.internalMoney = internalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.subcontract_payment
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.subcontract_payment
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public BigDecimal getSubcontractPayment() {
        return subcontractPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.subcontract_payment
     *
     * @param subcontractPayment the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.subcontract_payment
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setSubcontractPayment(BigDecimal subcontractPayment) {
        this.subcontractPayment = subcontractPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.includ_self_payment
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.includ_self_payment
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public BigDecimal getIncludSelfPayment() {
        return includSelfPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.includ_self_payment
     *
     * @param includSelfPayment the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.includ_self_payment
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setIncludSelfPayment(BigDecimal includSelfPayment) {
        this.includSelfPayment = includSelfPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.AnnualPurchaseRemaindAmount
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.AnnualPurchaseRemaindAmount
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public BigDecimal getAnnualpurchaseremaindamount() {
        return annualpurchaseremaindamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.AnnualPurchaseRemaindAmount
     *
     * @param annualpurchaseremaindamount the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.AnnualPurchaseRemaindAmount
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setAnnualpurchaseremaindamount(BigDecimal annualpurchaseremaindamount) {
        this.annualpurchaseremaindamount = annualpurchaseremaindamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.DeptDailyRemaindAmount
     *
     * @return the value of PR_FINANCE_CAPITAL_ANNUAL_DEPT.DeptDailyRemaindAmount
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public BigDecimal getDeptdailyremaindamount() {
        return deptdailyremaindamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PR_FINANCE_CAPITAL_ANNUAL_DEPT.DeptDailyRemaindAmount
     *
     * @param deptdailyremaindamount the value for PR_FINANCE_CAPITAL_ANNUAL_DEPT.DeptDailyRemaindAmount
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    public void setDeptdailyremaindamount(BigDecimal deptdailyremaindamount) {
        this.deptdailyremaindamount = deptdailyremaindamount;
    }
}