package com.rongwei.pims.job.dao;

import com.rongwei.pims.job.domain.AcOperator;

public interface AcOperatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AC_OPERATOR
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    int deleteByPrimaryKey(Long operatorid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AC_OPERATOR
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    int insert(AcOperator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AC_OPERATOR
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    int insertSelective(AcOperator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AC_OPERATOR
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    AcOperator selectByPrimaryKey(Long operatorid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AC_OPERATOR
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    int updateByPrimaryKeySelective(AcOperator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AC_OPERATOR
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    int updateByPrimaryKey(AcOperator record);
}