package com.rongwei.pims.job.dao;

import com.rongwei.pims.job.domain.MmContractProject;

public interface MmContractProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MM_ContractProjectSplit
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    int deleteByPrimaryKey(Integer contractprojectsplitid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MM_ContractProjectSplit
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    int insert(MmContractProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MM_ContractProjectSplit
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    int insertSelective(MmContractProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MM_ContractProjectSplit
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    MmContractProject selectByPrimaryKey(Integer contractprojectsplitid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MM_ContractProjectSplit
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    int updateByPrimaryKeySelective(MmContractProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MM_ContractProjectSplit
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    int updateByPrimaryKey(MmContractProject record);
}