package com.rongwei.pims.job.dao;

import com.rongwei.pims.job.domain.MmProjectAnnualDailyExpenses;

public interface MmProjectAnnualDailyExpensesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MM_Project_Annual_Daily_Expenses
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    int deleteByPrimaryKey(Integer projectannualdailyexpensesid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MM_Project_Annual_Daily_Expenses
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    int insert(MmProjectAnnualDailyExpenses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MM_Project_Annual_Daily_Expenses
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    int insertSelective(MmProjectAnnualDailyExpenses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MM_Project_Annual_Daily_Expenses
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    MmProjectAnnualDailyExpenses selectByPrimaryKey(Integer projectannualdailyexpensesid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MM_Project_Annual_Daily_Expenses
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    int updateByPrimaryKeySelective(MmProjectAnnualDailyExpenses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MM_Project_Annual_Daily_Expenses
     *
     * @mbg.generated Wed Apr 15 14:34:01 CST 2020
     */
    int updateByPrimaryKey(MmProjectAnnualDailyExpenses record);
}