package com.rongwei.pims.job.dao;

import com.rongwei.pims.job.domain.PrFinanceCapitalAnnualDept;

public interface PrFinanceCapitalAnnualDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PR_FINANCE_CAPITAL_ANNUAL_DEPT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    int deleteByPrimaryKey(Integer financeCapitalAnnualDeptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PR_FINANCE_CAPITAL_ANNUAL_DEPT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    int insert(PrFinanceCapitalAnnualDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PR_FINANCE_CAPITAL_ANNUAL_DEPT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    int insertSelective(PrFinanceCapitalAnnualDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PR_FINANCE_CAPITAL_ANNUAL_DEPT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    PrFinanceCapitalAnnualDept selectByPrimaryKey(Integer financeCapitalAnnualDeptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PR_FINANCE_CAPITAL_ANNUAL_DEPT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    int updateByPrimaryKeySelective(PrFinanceCapitalAnnualDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PR_FINANCE_CAPITAL_ANNUAL_DEPT
     *
     * @mbg.generated Tue Apr 21 16:44:44 CST 2020
     */
    int updateByPrimaryKey(PrFinanceCapitalAnnualDept record);
}